import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-quicksand",
});

export const metadata: Metadata = {
    title: "Career Laksh",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${quicksand.variable}`}>
                {children}
                <Script
                    src="https://www.googletagmanager.com/gtag/js?id=AW-16965899661"
                    strategy="afterInteractive"
                />

                <Script id="google-ads-gtag" strategy="afterInteractive">
                    {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-16965899661');
  `}
                </Script>
            </body>
        </html>
    );
}
